config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'habits#index'
  resources :habits, only: [:show, :create]
  resources :days, only: [:index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
    validates :logs_date, uniqueness: true, presence: true
    has_many :logs
    has_many :habits, through: :logs
end

app/models/habit.rb
class Habit < ApplicationRecord
    has_many :logs
    has_many :days, through: :logs
    validates :name, uniqueness: true, presence: true

    # returns a boolean array with the log info of the last 5 days
    def current_streak
        log_history = self.days.map {|day| day.logs_date }
        log_history.sort! {|a, b| b <=> a }
        log_history = log_history[0..4]

        days_since_habit_creation = (Time.now.to_date - self.created_at.to_date).to_i
        max_streak = days_since_habit_creation >= 5 ? -4 : -days_since_habit_creation
        recent_days = []
        (max_streak..0).each { |days| recent_days.push(Time.new.to_date + days) }

        recent_days.map { |day| log_history.include? day }
    end
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :habit
  belongs_to :day
  validates :habit, uniqueness: { scope: :day }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
    def index
        @days = Day.all
    end
    
    def show
        # handles when the user use the date selector (days/partials/date_selector)
        # or picks a date by clicking directly on a date link
        if params[:day].present?
            @day = Day.find_by(logs_date: params[:day][:logs_date])
        else
            @day = Day.find(params[:id])
        end
    end

    def create
        if Day.exists?(day_params)
            @day = Day.find_by(day_params)
        else 
            @day = Day.create(day_params)
        end

        @habit = Habit.find(params[:habit])
        @day.logs.create(habit: @habit)
        
        redirect_to habit_path(@habit)
    end

    private
    
    def day_params
        params.require(:day).permit(:logs_date)
    end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
    def index
        @habit = Habit.new
        @habits = Habit.all
    end

    def show
        @day = Day.new
        @habit = Habit.find(params[:id])
    end

    def create
        @habit = Habit.new(habit_params)
        if @habit.save
            redirect_to habit_path(@habit)
        else
            redirect_to root_path
        end
    end

    private

    def habit_params
        params.require(:habit).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/days/index.html.erb
<div class="card habit-card big-card">
    <h3>Pick a date</h3>
    <div class="log-history">
        <% unless @days.length == 0 %>
            <% log_history = @days.sort {|a, b| b.logs_date <=> a.logs_date} %>
            <% log_history.each do |day| %>
                <%= link_to day_path(day) do %>
                    <div class="card-body small-shadow-card">
                        <%= day.logs_date.strftime(day.logs_date.year < Time.new.year ? "%b %d, %Y" : "%b %d") %>
                    </div>
                <% end %>
            <% end %>
        <% else %>
            <h5>You haven't logged any habit yet!</h5>
        <% end %>
    </div>
<div>

app/views/days/partials/_create_edit_form.html.erb
<%= simple_form_for @day, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
    <%= f.input :logs_date, label: false, as: :date, html5: true, required: true, class: "form-control" %>
    <%= hidden_field_tag 'habit', @habit.id  %>
    <%= f.button :submit, "add log", class: "btn orange-btn small-btn" %>
<% end %>

app/views/days/partials/_date_selector.html.erb
<%= simple_form_for Day.new, method: :get, url: day_path(Day.first), wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
    <%= f.input :logs_date, label: false, as: :date, html5: true, required: true, class: "form-control" %>
    <%= f.button :submit, "pick date", class: "btn orange-btn small-btn" %>
<% end %>

app/views/days/show.html.erb
<div class="card habit-card big-card">
    <% if @day %>
        <h3>Habits logged on <%= @day.logs_date.strftime(@day.logs_date.year < Time.new.year ? "%b %d from %Y" : "%b %d") %></h3>
        <div class="d-flex">
        <%= render "days/partials/date_selector"%>
        <div class="log-history ml-5">  
            <% @day.habits.each do |habit| %>
                <%= link_to habit_path(habit) do %>
                    <div class="card-body small-shadow-card">
                        <%= habit.name.downcase %>
                    </div>
                <% end %>
            <% end %>
        </div>
    <% else %>
        <h3>No data for the given date</h3>
        <%= render "days/partials/date_selector"%>
    <% end %>
</div>

app/views/habits/index.html.erb
<%= button_tag 'habit +', class: "orange-btn btn", "data-toggle"=>"modal", "data-target"=>"#newHabitModal", type: "button" %>
  
<div id="habits-container">
  <% @habits.each do |habit| %>
    <%= link_to habit_path(habit) do %>
      <div class="card habit-card">
        <div class="card-body">
          <h5 class="card-title"><%= habit.name.capitalize %></h3>
          <h6 class="card-subtitle">current streak</h5>
          <ul class="inline-list">
              <% habit.current_streak.each do |log| %>
                  <% if log %>
                    <li class="big-dot green-dot">.</li>
                  <% else %>
                    <li class="big-dot red-dot">.</li>
                  <% end %>
              <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="newHabitModal" tabindex="-1" role="dialog" aria-labelledby="newHabitModalLabel" aria-hidden="true">
  <div class="modal-dialog custom-modal" role="document">
    <div class="modal-content">
      <div class="modal-header lightseagreen-modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New habit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "habits/partials/create_edit_form" %>
      </div>
    </div>
  </div>
</div>

app/views/habits/partials/_create_edit_form.html.erb
<%= simple_form_for @habit do |f| %>
    <%= f.input :name, label: false, required: true, class: "form-control" %>
    <%= f.button :submit, "create", class: "orange-btn small-btn" %>
<% end %>

app/views/habits/show.html.erb
<div class="card habit-card big-card">
    <h3><%= @habit.name.capitalize %></h3>
    <%= render '/days/partials/create_edit_form' %>
    <h5 class="align-self-start mt-3">Completed on:</h5>
    <div class="log-history">
        <% unless @habit.days.length == 0 %>
            <% log_history = @habit.days.sort {|a, b| b.logs_date <=> a.logs_date} %>
            <% log_history.each do |day| %>
                <%= link_to day_path(day) do %>
                    <div class="card-body small-shadow-card">
                        <%= day.logs_date.strftime(day.logs_date.year < Time.new.year ? "%b %d, %Y" : "%b %d") %>
                    </div>
                <% end %>
            <% end %>
        <% else %>
            <h5>Time to log your first time completing this habit!</h5>
        <% end %>
    </div>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Good Habits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/partials/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-telos">
    <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag(image_path "telos-labs.png")  %>
    <% end %>

    <div>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "My habits", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Date logs", days_path, class: "nav-link" %>
            </li>
        </ul>
    </div>
</div>